#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

ARG DRUID_RELEASE
FROM $DRUID_RELEASE

WORKDIR /opt/druid/extensions/mysql-metadata-storage

ARG MARIA_URL=https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/3.5.10/mariadb-java-client-3.5.10.jar
ARG MARIA_JAR=mariadb-java-client-3.5.10.jar
ARG MARIA_SHA=c6a687f7ccb65394103cd516e0583e61e6d92c24

RUN wget -q ${MARIA_URL} \
 && echo "${MARIA_SHA}  ${MARIA_JAR}" | sha1sum -c \
 && ln -s ../extensions/mysql-metadata-storage/${MARIA_JAR} /opt/druid/lib

WORKDIR /opt/druid
