/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.druid.msq.dart.worker.http;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.druid.msq.dart.controller.ControllerServerId;
import org.apache.druid.msq.dart.controller.http.DartQueryInfo;
import org.apache.druid.msq.dart.worker.WorkerId;
import org.joda.time.DateTime;

/**
 * Class included in {@link GetWorkersResponse}.
 */
public class DartWorkerInfo
{
  private final String dartQueryId;
  private final WorkerId workerId;
  private final ControllerServerId controllerServerId;
  private final DateTime startTime;

  public DartWorkerInfo(
      @JsonProperty("dartQueryId") final String dartQueryId,
      @JsonProperty("workerId") final WorkerId workerId,
      @JsonProperty("controllerServerId") final ControllerServerId controllerServerId,
      @JsonProperty("startTime") final DateTime startTime
  )
  {
    this.dartQueryId = dartQueryId;
    this.workerId = workerId;
    this.controllerServerId = controllerServerId;
    this.startTime = startTime;
  }

  /**
   * Dart query ID generated by the system. Globally unique.
   */
  @JsonProperty
  public String getDartQueryId()
  {
    return dartQueryId;
  }

  /**
   * Worker ID for this query.
   */
  @JsonProperty
  public WorkerId getWorkerId()
  {
    return workerId;
  }

  /**
   * Controller server that manages this query.
   */
  @JsonProperty
  public ControllerServerId getControllerHost()
  {
    return controllerServerId;
  }

  /**
   * Time this query was accepted by this worker. May be somewhat later than the {@link DartQueryInfo#getStartTime()}
   * on the controller.
   */
  @JsonProperty
  public DateTime getStartTime()
  {
    return startTime;
  }
}
