/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.druid.delta.input;

import com.google.common.collect.ImmutableList;
import org.apache.druid.data.input.ColumnsFilter;
import org.apache.druid.data.input.InputRowSchema;
import org.apache.druid.data.input.impl.DimensionsSpec;
import org.apache.druid.data.input.impl.LongDimensionSchema;
import org.apache.druid.data.input.impl.StringDimensionSchema;
import org.apache.druid.data.input.impl.TimestampSpec;

/**
 * Descriptor for a Delta table with 2 Parquet files × 2000 rows = 4000 rows total.
 *
 * Each file has more than 1024 rows, ensuring the Delta kernel reads more than one
 * batch per file. Used as a regression test for GH-18606 where
 * {@link DeltaInputSourceReader} only returned the first 1024 rows per file.
 *
 * Generated by src/test/resources/create_delta_table.py (large-row-group-table).
 */
public class LargeRowGroupDeltaTable
{
  public static final String DELTA_TABLE_PATH =
      "src/test/resources/large-row-group-table";

  public static final int EXPECTED_ROW_COUNT = 4000;

  public static final InputRowSchema SCHEMA = new InputRowSchema(
      new TimestampSpec("id", "posix", null),
      new DimensionsSpec(ImmutableList.of(
          new LongDimensionSchema("id"),
          new StringDimensionSchema("name")
      )),
      ColumnsFilter.all()
  );
}