version: 2
updates:
  # Don't run dependabot on website
  - package-ecosystem: "npm"
    directory: "/website/"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]
