version: 2
updates:
  # Don't run dependabot on website
  - package-ecosystem: "npm"
    directory: "/website/"
    schedule:
      interval: "monthly"        # minimal frequency
    open-pull-requests-limit: 0  # do not open PRs
