version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.google.guava:guava"
      # pin ZooKeeper dependencies to 3.5.x
      - dependency-name: "org.apache.zookeeper"
        versions: "[3.6,)"
