#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
set -x

RUNS=8

OPTS="-Dsurefire.failIfNoSpecifiedTests=false -Pci,skip-static-checks -Dweb.console.skip=true"
OPTS+=" -B -Dmaven.test.failure.ignore=true"
OPTS+=" -Dorg.slf4j.simpleLogger.defaultLogLevel=warn"
OPTS+=" -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugin.surefire=info"
OPTS+=" -Dsurefire.rerunFailingTestsCount=0"

TASK_LOGS="$(pwd)/task-logs"
RESULTS="stability-results"

# Expand per-run archives at EXIT so they are directly accessible after run
expand_archives() {
    shopt -s nullglob
    for archive in "$RESULTS"/run*.tar; do
        dir="${archive%.tar}"
        mkdir -p "$dir"
        tar -xf "$archive" -C "$dir" && rm "$archive"
    done
    shopt -u nullglob
}
trap expand_archives EXIT

# Build the module under test and its dependencies without running tests.
mvn -am -DskipTests $OPTS "$@" install

for i in $(seq 1 "$RUNS"); do
    echo "=== Stability run ${i}/${RUNS} ==="

    mkdir -p "$TASK_LOGS"
    mvn $OPTS "-Dtask.logs.dir=${TASK_LOGS}" "$@" test

    mkdir -p "$RESULTS"

    # Archive matched paths into a per-run tarball - will be expanded on exit
    shopt -s globstar nullglob
    tar -cf "$RESULTS/run${i}.tar" --remove-files **/target/surefire-reports task-logs
    shopt -u globstar nullglob

done
