image: eu.gcr.io/ligatus-prod-public-registry/generic-build-agent:latest

stages:
  - build

build:
  stage: build
  script:
  - rm -f ~/.m2/settings.xml
  - mvn clean install -DskipTests -Pdist,bundle-contrib-exts --quiet
  - gsutil -m cp distribution/target/*.tar.gz gs://lqm-artifact/${CI_PROJECT_NAME}/${CI_COMMIT_SHA}
