extraction:
  java:
    index:
      build_command: |
        mvn clean package
        -f "pom.xml"
        -B
        -V
        -e
        -Dfindbugs.skip
        -Dcheckstyle.skip
        -Dpmd.skip=true
        -Denforcer.skip
        -Dmaven.javadoc.skip
        -DskipTests
        -Dmaven.test.skip.exec
        -Dlicense.skip=true
        -Ddruid.console.skip=true
        -Dmaven.repo.local=${semmle_data}/maven_repo
        -t /opt/work/.m2/toolchains.xml
