#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#--------------------------------------------------------------------

# Utility script for running the new integration tests, since the Maven
# commands are unwieldy. Allows straightforward usage of ITs on the desktop
# and in various build scripts. Handles configuration of various kinds.


set -e

OPTS+=" -Pskip-static-checks"
OPTS+=" -Dsurefire.rerunFailingTestsCount=0"
OPTS+=" -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugin.surefire.SurefirePlugin=INFO"
[[ $@ =~ "-q" ]] && OPTS+=" -Dsurefire.trimStackTrace=true"

OPTS+=" -pl sql -Dtest=SqlQuidemTest"
OPTS+=" org.apache.maven.plugins:maven-surefire-plugin:test"

case "$1" in
 -h|--help)
	cat << EOF
Run SqlQuidemTest tests.
  -q				quiet (recommened)
  -Dquidem.overwrite		enables overwrite mode
  -Dquidem.filter=*join*	runs only tests matching path expression
EOF
exit 1
	;;
esac

exec mvn "$@" $OPTS
