// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_nested_event.proto

// Protobuf Java Version: 3.25.8
package org.apache.druid.data.input.protobuf;

public final class ProtoNestedEventWrapper {
  private ProtoNestedEventWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prototest_ProtoNestedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prototest_ProtoNestedEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prototest_ProtoNestedEvent_MyMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prototest_ProtoNestedEvent_MyMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto_nested_event.proto\022\tprototest\032\034g" +
      "oogle/protobuf/struct.proto\"\203\002\n\020ProtoNes" +
      "tedEvent\022\021\n\ttimestamp\030\001 \001(\003\022\022\n\004name\030\002 \001(" +
      "\tR\004name\022\013\n\003log\030\003 \001(\t\0225\n\tmy_struct\030\004 \001(\0132" +
      "\027.google.protobuf.StructR\tmy_struct\022>\n\006m" +
      "y_map\030\005 \003(\0132&.prototest.ProtoNestedEvent" +
      ".MyMapEntryR\006my_map\032D\n\nMyMapEntry\022\013\n\003key" +
      "\030\001 \001(\t\022%\n\005value\030\002 \001(\0132\026.google.protobuf." +
      "Value:\0028\001BA\n$org.apache.druid.data.input" +
      ".protobufB\027ProtoNestedEventWrapperP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_prototest_ProtoNestedEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_prototest_ProtoNestedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prototest_ProtoNestedEvent_descriptor,
        new java.lang.String[] { "Timestamp", "Name", "Log", "MyStruct", "MyMap", });
    internal_static_prototest_ProtoNestedEvent_MyMapEntry_descriptor =
      internal_static_prototest_ProtoNestedEvent_descriptor.getNestedTypes().get(0);
    internal_static_prototest_ProtoNestedEvent_MyMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prototest_ProtoNestedEvent_MyMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
