// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_nested_event.proto

// Protobuf Java Version: 3.25.8
package org.apache.druid.data.input.protobuf;

/**
 * Protobuf type {@code prototest.ProtoNestedEvent}
 */
public final class ProtoNestedEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:prototest.ProtoNestedEvent)
    ProtoNestedEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoNestedEvent.newBuilder() to construct.
  private ProtoNestedEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoNestedEvent() {
    name_ = "";
    log_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoNestedEvent();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.druid.data.input.protobuf.ProtoNestedEventWrapper.internal_static_prototest_ProtoNestedEvent_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 5:
        return internalGetMyMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.druid.data.input.protobuf.ProtoNestedEventWrapper.internal_static_prototest_ProtoNestedEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.druid.data.input.protobuf.ProtoNestedEvent.class, org.apache.druid.data.input.protobuf.ProtoNestedEvent.Builder.class);
  }

  private int bitField0_;
  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOG_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object log_ = "";
  /**
   * <code>string log = 3;</code>
   * @return The log.
   */
  @java.lang.Override
  public java.lang.String getLog() {
    java.lang.Object ref = log_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      log_ = s;
      return s;
    }
  }
  /**
   * <code>string log = 3;</code>
   * @return The bytes for log.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLogBytes() {
    java.lang.Object ref = log_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      log_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MY_STRUCT_FIELD_NUMBER = 4;
  private com.google.protobuf.Struct myStruct_;
  /**
   * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
   * @return Whether the myStruct field is set.
   */
  @java.lang.Override
  public boolean hasMyStruct() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
   * @return The myStruct.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getMyStruct() {
    return myStruct_ == null ? com.google.protobuf.Struct.getDefaultInstance() : myStruct_;
  }
  /**
   * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getMyStructOrBuilder() {
    return myStruct_ == null ? com.google.protobuf.Struct.getDefaultInstance() : myStruct_;
  }

  public static final int MY_MAP_FIELD_NUMBER = 5;
  private static final class MyMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.Value> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.Value>newDefaultInstance(
                org.apache.druid.data.input.protobuf.ProtoNestedEventWrapper.internal_static_prototest_ProtoNestedEvent_MyMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.google.protobuf.Value.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.Value> myMap_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
  internalGetMyMap() {
    if (myMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MyMapDefaultEntryHolder.defaultEntry);
    }
    return myMap_;
  }
  public int getMyMapCount() {
    return internalGetMyMap().getMap().size();
  }
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
   */
  @java.lang.Override
  public boolean containsMyMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMyMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMyMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.Value> getMyMap() {
    return getMyMapMap();
  }
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.google.protobuf.Value> getMyMapMap() {
    return internalGetMyMap().getMap();
  }
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
   */
  @java.lang.Override
  public /* nullable */
com.google.protobuf.Value getMyMapOrDefault(
      java.lang.String key,
      /* nullable */
com.google.protobuf.Value defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.google.protobuf.Value> map =
        internalGetMyMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Value getMyMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.google.protobuf.Value> map =
        internalGetMyMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != 0L) {
      output.writeInt64(1, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(log_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, log_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getMyStruct());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMyMap(),
        MyMapDefaultEntryHolder.defaultEntry,
        5);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(log_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, log_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMyStruct());
    }
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Value> entry
         : internalGetMyMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
      myMap__ = MyMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, myMap__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.druid.data.input.protobuf.ProtoNestedEvent)) {
      return super.equals(obj);
    }
    org.apache.druid.data.input.protobuf.ProtoNestedEvent other = (org.apache.druid.data.input.protobuf.ProtoNestedEvent) obj;

    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getLog()
        .equals(other.getLog())) return false;
    if (hasMyStruct() != other.hasMyStruct()) return false;
    if (hasMyStruct()) {
      if (!getMyStruct()
          .equals(other.getMyStruct())) return false;
    }
    if (!internalGetMyMap().equals(
        other.internalGetMyMap())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + LOG_FIELD_NUMBER;
    hash = (53 * hash) + getLog().hashCode();
    if (hasMyStruct()) {
      hash = (37 * hash) + MY_STRUCT_FIELD_NUMBER;
      hash = (53 * hash) + getMyStruct().hashCode();
    }
    if (!internalGetMyMap().getMap().isEmpty()) {
      hash = (37 * hash) + MY_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMyMap().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.druid.data.input.protobuf.ProtoNestedEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code prototest.ProtoNestedEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:prototest.ProtoNestedEvent)
      org.apache.druid.data.input.protobuf.ProtoNestedEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.druid.data.input.protobuf.ProtoNestedEventWrapper.internal_static_prototest_ProtoNestedEvent_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 5:
          return internalGetMyMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableMyMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.druid.data.input.protobuf.ProtoNestedEventWrapper.internal_static_prototest_ProtoNestedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.druid.data.input.protobuf.ProtoNestedEvent.class, org.apache.druid.data.input.protobuf.ProtoNestedEvent.Builder.class);
    }

    // Construct using org.apache.druid.data.input.protobuf.ProtoNestedEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMyStructFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timestamp_ = 0L;
      name_ = "";
      log_ = "";
      myStruct_ = null;
      if (myStructBuilder_ != null) {
        myStructBuilder_.dispose();
        myStructBuilder_ = null;
      }
      internalGetMutableMyMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.druid.data.input.protobuf.ProtoNestedEventWrapper.internal_static_prototest_ProtoNestedEvent_descriptor;
    }

    @java.lang.Override
    public org.apache.druid.data.input.protobuf.ProtoNestedEvent getDefaultInstanceForType() {
      return org.apache.druid.data.input.protobuf.ProtoNestedEvent.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.druid.data.input.protobuf.ProtoNestedEvent build() {
      org.apache.druid.data.input.protobuf.ProtoNestedEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.druid.data.input.protobuf.ProtoNestedEvent buildPartial() {
      org.apache.druid.data.input.protobuf.ProtoNestedEvent result = new org.apache.druid.data.input.protobuf.ProtoNestedEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.druid.data.input.protobuf.ProtoNestedEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.log_ = log_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.myStruct_ = myStructBuilder_ == null
            ? myStruct_
            : myStructBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.myMap_ = internalGetMyMap().build(MyMapDefaultEntryHolder.defaultEntry);
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.druid.data.input.protobuf.ProtoNestedEvent) {
        return mergeFrom((org.apache.druid.data.input.protobuf.ProtoNestedEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.druid.data.input.protobuf.ProtoNestedEvent other) {
      if (other == org.apache.druid.data.input.protobuf.ProtoNestedEvent.getDefaultInstance()) return this;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getLog().isEmpty()) {
        log_ = other.log_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasMyStruct()) {
        mergeMyStruct(other.getMyStruct());
      }
      internalGetMutableMyMap().mergeFrom(
          other.internalGetMyMap());
      bitField0_ |= 0x00000010;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              log_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getMyStructFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
              myMap__ = input.readMessage(
                  MyMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMyMap().ensureBuilderMap().put(
                  myMap__.getKey(), myMap__.getValue());
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object log_ = "";
    /**
     * <code>string log = 3;</code>
     * @return The log.
     */
    public java.lang.String getLog() {
      java.lang.Object ref = log_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        log_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string log = 3;</code>
     * @return The bytes for log.
     */
    public com.google.protobuf.ByteString
        getLogBytes() {
      java.lang.Object ref = log_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        log_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string log = 3;</code>
     * @param value The log to set.
     * @return This builder for chaining.
     */
    public Builder setLog(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      log_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string log = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLog() {
      log_ = getDefaultInstance().getLog();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string log = 3;</code>
     * @param value The bytes for log to set.
     * @return This builder for chaining.
     */
    public Builder setLogBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      log_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct myStruct_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> myStructBuilder_;
    /**
     * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
     * @return Whether the myStruct field is set.
     */
    public boolean hasMyStruct() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
     * @return The myStruct.
     */
    public com.google.protobuf.Struct getMyStruct() {
      if (myStructBuilder_ == null) {
        return myStruct_ == null ? com.google.protobuf.Struct.getDefaultInstance() : myStruct_;
      } else {
        return myStructBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
     */
    public Builder setMyStruct(com.google.protobuf.Struct value) {
      if (myStructBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        myStruct_ = value;
      } else {
        myStructBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
     */
    public Builder setMyStruct(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (myStructBuilder_ == null) {
        myStruct_ = builderForValue.build();
      } else {
        myStructBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
     */
    public Builder mergeMyStruct(com.google.protobuf.Struct value) {
      if (myStructBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          myStruct_ != null &&
          myStruct_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getMyStructBuilder().mergeFrom(value);
        } else {
          myStruct_ = value;
        }
      } else {
        myStructBuilder_.mergeFrom(value);
      }
      if (myStruct_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
     */
    public Builder clearMyStruct() {
      bitField0_ = (bitField0_ & ~0x00000008);
      myStruct_ = null;
      if (myStructBuilder_ != null) {
        myStructBuilder_.dispose();
        myStructBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
     */
    public com.google.protobuf.Struct.Builder getMyStructBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getMyStructFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
     */
    public com.google.protobuf.StructOrBuilder getMyStructOrBuilder() {
      if (myStructBuilder_ != null) {
        return myStructBuilder_.getMessageOrBuilder();
      } else {
        return myStruct_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : myStruct_;
      }
    }
    /**
     * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getMyStructFieldBuilder() {
      if (myStructBuilder_ == null) {
        myStructBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getMyStruct(),
                getParentForChildren(),
                isClean());
        myStruct_ = null;
      }
      return myStructBuilder_;
    }

    private static final class MyMapConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.google.protobuf.ValueOrBuilder, com.google.protobuf.Value> {
      @java.lang.Override
      public com.google.protobuf.Value build(com.google.protobuf.ValueOrBuilder val) {
        if (val instanceof com.google.protobuf.Value) { return (com.google.protobuf.Value) val; }
        return ((com.google.protobuf.Value.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value> defaultEntry() {
        return MyMapDefaultEntryHolder.defaultEntry;
      }
    };
    private static final MyMapConverter myMapConverter = new MyMapConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.google.protobuf.ValueOrBuilder, com.google.protobuf.Value, com.google.protobuf.Value.Builder> myMap_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.google.protobuf.ValueOrBuilder, com.google.protobuf.Value, com.google.protobuf.Value.Builder>
        internalGetMyMap() {
      if (myMap_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(myMapConverter);
      }
      return myMap_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.google.protobuf.ValueOrBuilder, com.google.protobuf.Value, com.google.protobuf.Value.Builder>
        internalGetMutableMyMap() {
      if (myMap_ == null) {
        myMap_ = new com.google.protobuf.MapFieldBuilder<>(myMapConverter);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return myMap_;
    }
    public int getMyMapCount() {
      return internalGetMyMap().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
     */
    @java.lang.Override
    public boolean containsMyMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMyMap().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getMyMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Value> getMyMap() {
      return getMyMapMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.google.protobuf.Value> getMyMapMap() {
      return internalGetMyMap().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.Value getMyMapOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.Value defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ValueOrBuilder> map = internalGetMutableMyMap().ensureBuilderMap();
      return map.containsKey(key) ? myMapConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Value getMyMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ValueOrBuilder> map = internalGetMutableMyMap().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return myMapConverter.build(map.get(key));
    }
    public Builder clearMyMap() {
      bitField0_ = (bitField0_ & ~0x00000010);
      internalGetMutableMyMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
     */
    public Builder removeMyMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMyMap().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Value>
        getMutableMyMap() {
      bitField0_ |= 0x00000010;
      return internalGetMutableMyMap().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
     */
    public Builder putMyMap(
        java.lang.String key,
        com.google.protobuf.Value value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMyMap().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
     */
    public Builder putAllMyMap(
        java.util.Map<java.lang.String, com.google.protobuf.Value> values) {
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Value> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableMyMap().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
     */
    public com.google.protobuf.Value.Builder putMyMapBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.google.protobuf.ValueOrBuilder> builderMap = internalGetMutableMyMap().ensureBuilderMap();
      com.google.protobuf.ValueOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.google.protobuf.Value.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.google.protobuf.Value) {
        entry = ((com.google.protobuf.Value) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.google.protobuf.Value.Builder) entry;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:prototest.ProtoNestedEvent)
  }

  // @@protoc_insertion_point(class_scope:prototest.ProtoNestedEvent)
  private static final org.apache.druid.data.input.protobuf.ProtoNestedEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.druid.data.input.protobuf.ProtoNestedEvent();
  }

  public static org.apache.druid.data.input.protobuf.ProtoNestedEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoNestedEvent>
      PARSER = new com.google.protobuf.AbstractParser<ProtoNestedEvent>() {
    @java.lang.Override
    public ProtoNestedEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProtoNestedEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoNestedEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.druid.data.input.protobuf.ProtoNestedEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

