// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_nested_event.proto

// Protobuf Java Version: 3.25.8
package org.apache.druid.data.input.protobuf;

public interface ProtoNestedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:prototest.ProtoNestedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string log = 3;</code>
   * @return The log.
   */
  java.lang.String getLog();
  /**
   * <code>string log = 3;</code>
   * @return The bytes for log.
   */
  com.google.protobuf.ByteString
      getLogBytes();

  /**
   * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
   * @return Whether the myStruct field is set.
   */
  boolean hasMyStruct();
  /**
   * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
   * @return The myStruct.
   */
  com.google.protobuf.Struct getMyStruct();
  /**
   * <code>.google.protobuf.Struct my_struct = 4 [json_name = "my_struct"];</code>
   */
  com.google.protobuf.StructOrBuilder getMyStructOrBuilder();

  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
   */
  int getMyMapCount();
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
   */
  boolean containsMyMap(
      java.lang.String key);
  /**
   * Use {@link #getMyMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.Value>
  getMyMap();
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.Value>
  getMyMapMap();
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
   */
  /* nullable */
com.google.protobuf.Value getMyMapOrDefault(
      java.lang.String key,
      /* nullable */
com.google.protobuf.Value defaultValue);
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; my_map = 5 [json_name = "my_map"];</code>
   */
  com.google.protobuf.Value getMyMapOrThrow(
      java.lang.String key);
}
