#!/bin/bash

set -e

find . -name 'TEST*xml' |
# <testsuite ... name="org.apache.druid.query.policy.NoRestrictionPolicyTest" time="0.071" ...>
xargs sed -nr '/^<testsuite/s/.*name=\"([^\"]+)\".*time=\"([^\"]+)\".*/\1\t\2/p' |
# org.apache.druid.server.RequestLogLineTest      0.052
sed -r 's/[^\t]+\.(.)[^\t.]+\t/\1\t/' > test_times

for c in {A..Z} ;do
 echo -n "$c    ";
 (echo 0;grep "^$c" test_times| cut -f 2)|paste -s -d + -|bc
done | sort -k 2 -nr


