#!/bin/bash

# Updates the versions for the master branch

[ "$#" -lt 1 ] && echo "usage: $0 <new_version>" && exit 1

set -e
set -x

VERSION=$1
DOCS_VERSION=latest

sed -i -r "s|public/web-console-[^<]+.js|public/web-console-${VERSION}.js|" web-console/unified-console.html
sed -i -r "s|DRUID_DOCS_VERSION = '[^']+'|DRUID_DOCS_VERSION = '${DOCS_VERSION}'|" web-console/src/links.ts
sed -i -r "s|apache/druid:[0-9\.]+|apache/druid:${VERSION}|" distribution/docker/docker-compose.yml

# make node available to shell
mvn install -pl web-console -DskipTests
export PATH+=:$PWD/web-console/target/node/

cd web-console
npm version $VERSION
npm install
npm run jest -- -u
cd ..
mvn -q versions:set -DnewVersion=${VERSION}-SNAPSHOT

echo ok
