#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#--------------------------------------------------------------------

set -e

git grep junit-jupiter-engine '**/pom.xml' | cut -d: -f1 | while read pom ;do

	m=`dirname $pom`
	hasj4=`git grep org.junit.Test $m | head -n 1 | wc -l`
	hasVintage=`git grep junit-vintage-engine $m|head -n 1 | wc -l`

	echo "$m hasj4:$hasj4 hasVintage:$hasVintage"

	if [ "$hasVintage" != "$hasj4" ];then
		echo "Module [$m] is configured to use junit5 but its configured is not valid!"
		echo " has_junit4_tests[$hasj4] <> has_vintage_engine[$hasVintage] !"
		echo
		echo "The junit4/5 migration guide might be helpfull https://www.baeldung.com/junit-5-migration"
		echo "Possibly usefull openrewrite docs: https://docs.openrewrite.org/recipes/java/testing/junit5/junit4to5migration"
		exit 1
	fi
done
