#!/bin/bash -eu

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

# If needed, build SQL docs
# Building SQL docs is needed if an argument of `--force` is given to this script, or the file lib/sql-docs.ts does not exist, or if that file has an earlier last modified time than any of the source files used to build the SQL docs which are:
#
# ./script/create-sql-docs.mjs
# script/sql-doc-files.txt
# Any file listed in script/sql-doc-files.txt

echo "Compiling SQL function docs for the web console..."
./script/create-sql-docs.mjs

# End if

# If needed, build the console
# Building the console is needed if an argument of `--force` is given to this script, or the file public/web-console-{{VERSION}}.js does not exist, or if that file has an earlier modified time than any of the files {src,lib}/**/*.{ts,tsx} where the VERSION is taken as the "version" in package.json or any of these files
#
# package.json
# package-lock.json
# webpack.config.mjs
# tsconfig.json

echo "Webpacking everything..."
NODE_ENV=production ./node_modules/.bin/webpack -c webpack.config.mjs --mode=production

# End if

echo "Web console building finished."
