/*
 * Licensed to Metamarkets Group Inc. (Metamarkets) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. Metamarkets licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoTest.proto

package io.druid.data.input;

import com.google.protobuf.AbstractMessage;
import com.google.protobuf.UnknownFieldSet;

public final class ProtoTestEventWrapper {
  private ProtoTestEventWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtoTestEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .prototest.ProtoTestEvent.EventCategory eventType = 1;
    boolean hasEventType();
    ProtoTestEventWrapper.ProtoTestEvent.EventCategory getEventType();
    
    // required uint64 id = 2;
    boolean hasId();
    long getId();
    
    // required string timestamp = 3;
    boolean hasTimestamp();
    String getTimestamp();
    
    // optional uint32 someOtherId = 4;
    boolean hasSomeOtherId();
    int getSomeOtherId();
    
    // optional bool isValid = 5;
    boolean hasIsValid();
    boolean getIsValid();
    
    // optional string description = 6;
    boolean hasDescription();
    String getDescription();
    
    // optional float someFloatColumn = 7;
    boolean hasSomeFloatColumn();
    float getSomeFloatColumn();
    
    // optional uint32 someIntColumn = 8;
    boolean hasSomeIntColumn();
    int getSomeIntColumn();
    
    // optional uint64 someLongColumn = 9;
    boolean hasSomeLongColumn();
    long getSomeLongColumn();
  }
  public static final class ProtoTestEvent extends
      com.google.protobuf.GeneratedMessage
      implements ProtoTestEventOrBuilder {
    // Use ProtoTestEvent.newBuilder() to construct.
    private ProtoTestEvent(Builder builder) {
      super(builder);
    }
    private ProtoTestEvent(boolean noInit) {}
    
    private static final ProtoTestEvent defaultInstance;
    public static ProtoTestEvent getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProtoTestEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    @Override
    public UnknownFieldSet getUnknownFields()
    {
      return UnknownFieldSet.getDefaultInstance();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoTestEventWrapper.internal_static_prototest_ProtoTestEvent_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoTestEventWrapper.internal_static_prototest_ProtoTestEvent_fieldAccessorTable;
    }
    
    public enum EventCategory
        implements com.google.protobuf.ProtocolMessageEnum {
      CATEGORY_ZERO(0, 0),
      CATEGORY_ONE(1, 1),
      CATEGORY_TWO(2, 2),
      ;
      
      public static final int CATEGORY_ZERO_VALUE = 0;
      public static final int CATEGORY_ONE_VALUE = 1;
      public static final int CATEGORY_TWO_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static EventCategory valueOf(int value) {
        switch (value) {
          case 0: return CATEGORY_ZERO;
          case 1: return CATEGORY_ONE;
          case 2: return CATEGORY_TWO;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<EventCategory>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EventCategory>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventCategory>() {
              public EventCategory findValueByNumber(int number) {
                return EventCategory.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ProtoTestEventWrapper.ProtoTestEvent.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final EventCategory[] VALUES = {
        CATEGORY_ZERO, CATEGORY_ONE, CATEGORY_TWO, 
      };
      
      public static EventCategory valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private EventCategory(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:prototest.ProtoTestEvent.EventCategory)
    }
    
    private int bitField0_;
    // required .prototest.ProtoTestEvent.EventCategory eventType = 1;
    public static final int EVENTTYPE_FIELD_NUMBER = 1;
    private ProtoTestEventWrapper.ProtoTestEvent.EventCategory eventType_;
    public boolean hasEventType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public ProtoTestEventWrapper.ProtoTestEvent.EventCategory getEventType() {
      return eventType_;
    }
    
    // required uint64 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getId() {
      return id_;
    }
    
    // required string timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private java.lang.Object timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          timestamp_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint32 someOtherId = 4;
    public static final int SOMEOTHERID_FIELD_NUMBER = 4;
    private int someOtherId_;
    public boolean hasSomeOtherId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getSomeOtherId() {
      return someOtherId_;
    }
    
    // optional bool isValid = 5;
    public static final int ISVALID_FIELD_NUMBER = 5;
    private boolean isValid_;
    public boolean hasIsValid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getIsValid() {
      return isValid_;
    }
    
    // optional string description = 6;
    public static final int DESCRIPTION_FIELD_NUMBER = 6;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional float someFloatColumn = 7;
    public static final int SOMEFLOATCOLUMN_FIELD_NUMBER = 7;
    private float someFloatColumn_;
    public boolean hasSomeFloatColumn() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public float getSomeFloatColumn() {
      return someFloatColumn_;
    }
    
    // optional uint32 someIntColumn = 8;
    public static final int SOMEINTCOLUMN_FIELD_NUMBER = 8;
    private int someIntColumn_;
    public boolean hasSomeIntColumn() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getSomeIntColumn() {
      return someIntColumn_;
    }
    
    // optional uint64 someLongColumn = 9;
    public static final int SOMELONGCOLUMN_FIELD_NUMBER = 9;
    private long someLongColumn_;
    public boolean hasSomeLongColumn() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public long getSomeLongColumn() {
      return someLongColumn_;
    }
    
    private void initFields() {
      eventType_ = ProtoTestEventWrapper.ProtoTestEvent.EventCategory.CATEGORY_ZERO;
      id_ = 0L;
      timestamp_ = "";
      someOtherId_ = 0;
      isValid_ = false;
      description_ = "";
      someFloatColumn_ = 0F;
      someIntColumn_ = 0;
      someLongColumn_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasEventType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, eventType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, someOtherId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, isValid_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, someFloatColumn_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(8, someIntColumn_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt64(9, someLongColumn_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, eventType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, someOtherId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isValid_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, someFloatColumn_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, someIntColumn_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, someLongColumn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ProtoTestEventWrapper.ProtoTestEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoTestEventWrapper.ProtoTestEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoTestEventWrapper.ProtoTestEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoTestEventWrapper.ProtoTestEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoTestEventWrapper.ProtoTestEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoTestEventWrapper.ProtoTestEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtoTestEventWrapper.ProtoTestEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoTestEventWrapper.ProtoTestEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoTestEventWrapper.ProtoTestEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoTestEventWrapper.ProtoTestEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoTestEventWrapper.ProtoTestEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoTestEventWrapper.ProtoTestEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoTestEventWrapper.internal_static_prototest_ProtoTestEvent_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoTestEventWrapper.internal_static_prototest_ProtoTestEvent_fieldAccessorTable;
      }
      
      // Construct using io.druid.data.input.ProtoTestEventWrapper.ProtoTestEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        eventType_ = ProtoTestEventWrapper.ProtoTestEvent.EventCategory.CATEGORY_ZERO;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        someOtherId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        isValid_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        someFloatColumn_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        someIntColumn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        someLongColumn_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoTestEventWrapper.ProtoTestEvent.getDescriptor();
      }
      
      public ProtoTestEventWrapper.ProtoTestEvent getDefaultInstanceForType() {
        return ProtoTestEventWrapper.ProtoTestEvent.getDefaultInstance();
      }
      
      public ProtoTestEventWrapper.ProtoTestEvent build() {
        ProtoTestEventWrapper.ProtoTestEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ProtoTestEventWrapper.ProtoTestEvent buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ProtoTestEventWrapper.ProtoTestEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(
              result
          ).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ProtoTestEventWrapper.ProtoTestEvent buildPartial() {
        ProtoTestEventWrapper.ProtoTestEvent result = new ProtoTestEventWrapper.ProtoTestEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.eventType_ = eventType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.someOtherId_ = someOtherId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.isValid_ = isValid_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.someFloatColumn_ = someFloatColumn_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.someIntColumn_ = someIntColumn_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.someLongColumn_ = someLongColumn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoTestEventWrapper.ProtoTestEvent) {
          return mergeFrom((ProtoTestEventWrapper.ProtoTestEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtoTestEventWrapper.ProtoTestEvent other) {
        if (other == ProtoTestEventWrapper.ProtoTestEvent.getDefaultInstance()) return this;
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasSomeOtherId()) {
          setSomeOtherId(other.getSomeOtherId());
        }
        if (other.hasIsValid()) {
          setIsValid(other.getIsValid());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasSomeFloatColumn()) {
          setSomeFloatColumn(other.getSomeFloatColumn());
        }
        if (other.hasSomeIntColumn()) {
          setSomeIntColumn(other.getSomeIntColumn());
        }
        if (other.hasSomeLongColumn()) {
          setSomeLongColumn(other.getSomeLongColumn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasEventType()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ProtoTestEventWrapper.ProtoTestEvent.EventCategory value = ProtoTestEventWrapper.ProtoTestEvent.EventCategory.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                eventType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readUInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              someOtherId_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              isValid_ = input.readBool();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              description_ = input.readBytes();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              someFloatColumn_ = input.readFloat();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              someIntColumn_ = input.readUInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              someLongColumn_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .prototest.ProtoTestEvent.EventCategory eventType = 1;
      private ProtoTestEventWrapper.ProtoTestEvent.EventCategory eventType_ = ProtoTestEventWrapper.ProtoTestEvent.EventCategory.CATEGORY_ZERO;
      public boolean hasEventType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public ProtoTestEventWrapper.ProtoTestEvent.EventCategory getEventType() {
        return eventType_;
      }
      public Builder setEventType(ProtoTestEventWrapper.ProtoTestEvent.EventCategory value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        eventType_ = value;
        onChanged();
        return this;
      }
      public Builder clearEventType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eventType_ = ProtoTestEventWrapper.ProtoTestEvent.EventCategory.CATEGORY_ZERO;
        onChanged();
        return this;
      }
      
      // required uint64 id = 2;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // required string timestamp = 3;
      private java.lang.Object timestamp_ = "";
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTimestamp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      void setTimestamp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
      }
      
      // optional uint32 someOtherId = 4;
      private int someOtherId_ ;
      public boolean hasSomeOtherId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getSomeOtherId() {
        return someOtherId_;
      }
      public Builder setSomeOtherId(int value) {
        bitField0_ |= 0x00000008;
        someOtherId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSomeOtherId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        someOtherId_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool isValid = 5;
      private boolean isValid_ ;
      public boolean hasIsValid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getIsValid() {
        return isValid_;
      }
      public Builder setIsValid(boolean value) {
        bitField0_ |= 0x00000010;
        isValid_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsValid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isValid_ = false;
        onChanged();
        return this;
      }
      
      // optional string description = 6;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000020);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        description_ = value;
        onChanged();
      }
      
      // optional float someFloatColumn = 7;
      private float someFloatColumn_ ;
      public boolean hasSomeFloatColumn() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public float getSomeFloatColumn() {
        return someFloatColumn_;
      }
      public Builder setSomeFloatColumn(float value) {
        bitField0_ |= 0x00000040;
        someFloatColumn_ = value;
        onChanged();
        return this;
      }
      public Builder clearSomeFloatColumn() {
        bitField0_ = (bitField0_ & ~0x00000040);
        someFloatColumn_ = 0F;
        onChanged();
        return this;
      }
      
      // optional uint32 someIntColumn = 8;
      private int someIntColumn_ ;
      public boolean hasSomeIntColumn() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getSomeIntColumn() {
        return someIntColumn_;
      }
      public Builder setSomeIntColumn(int value) {
        bitField0_ |= 0x00000080;
        someIntColumn_ = value;
        onChanged();
        return this;
      }
      public Builder clearSomeIntColumn() {
        bitField0_ = (bitField0_ & ~0x00000080);
        someIntColumn_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint64 someLongColumn = 9;
      private long someLongColumn_ ;
      public boolean hasSomeLongColumn() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public long getSomeLongColumn() {
        return someLongColumn_;
      }
      public Builder setSomeLongColumn(long value) {
        bitField0_ |= 0x00000100;
        someLongColumn_ = value;
        onChanged();
        return this;
      }
      public Builder clearSomeLongColumn() {
        bitField0_ = (bitField0_ & ~0x00000100);
        someLongColumn_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:prototest.ProtoTestEvent)
    }
    
    static {
      defaultInstance = new ProtoTestEvent(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:prototest.ProtoTestEvent)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_prototest_ProtoTestEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prototest_ProtoTestEvent_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ProtoTest.proto\022\tprototest\"\266\002\n\016ProtoTe" +
      "stEvent\022:\n\teventType\030\001 \002(\0162\'.prototest.P" +
      "rotoTestEvent.EventCategory\022\n\n\002id\030\002 \002(\004\022" +
      "\021\n\ttimestamp\030\003 \002(\t\022\023\n\013someOtherId\030\004 \001(\r\022" +
      "\017\n\007isValid\030\005 \001(\010\022\023\n\013description\030\006 \001(\t\022\027\n" +
      "\017someFloatColumn\030\007 \001(\002\022\025\n\rsomeIntColumn\030" +
      "\010 \001(\r\022\026\n\016someLongColumn\030\t \001(\004\"F\n\rEventCa" +
      "tegory\022\021\n\rCATEGORY_ZERO\020\000\022\020\n\014CATEGORY_ON" +
      "E\020\001\022\020\n\014CATEGORY_TWO\020\002B6\n\035com.metamx.drui" +
      "d.indexer.dataB\025ProtoTestEventWrapper"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_prototest_ProtoTestEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_prototest_ProtoTestEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_prototest_ProtoTestEvent_descriptor,
              new java.lang.String[] { "EventType", "Id", "Timestamp", "SomeOtherId", "IsValid", "Description", "SomeFloatColumn", "SomeIntColumn", "SomeLongColumn", },
              ProtoTestEventWrapper.ProtoTestEvent.class,
              ProtoTestEventWrapper.ProtoTestEvent.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  
  // @@protoc_insertion_point(outer_class_scope)
}
