# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# To build the image from this dockerfile: docker image build -t data-driver .
# To run the container: docker run -i data-driver SCRIPT_OPTIONS < CONFIG_FILE_NAME > OUTPUT_FILE_NAME
#     For example: docker run -i data-driver -n 3 < examples/simple_config.json > out.json

FROM python:3.10

WORKDIR /driver

RUN pip install python-dateutil \
  && pip install kafka-python \
  && pip install numpy

COPY DruidDataDriver.py .

ENTRYPOINT [ "python", "./DruidDataDriver.py"]
