/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.druid.data.input.pulsar;

import org.apache.druid.data.input.InputFormat;
import org.apache.druid.data.input.impl.ByteEntity;
import org.apache.druid.indexing.pulsar.PulsarRecordSupplier;
import org.apache.pulsar.client.api.Message;

/**
 * A {@link ByteEntity} generated by {@link PulsarRecordSupplier} and fed to any {@link InputFormat} used by Pulsar
 * indexing tasks.
 * <p>
 * It can be used as a regular ByteEntity, in which case the Pulsar message value is returned, but the {@link #getMessage}
 * method also allows Pulsar-aware {@link InputFormat} implementations to read the full Pulsar message, including headers,
 * key, and timestamp.
 * <p>
 * NOTE: Any messages with null values will be skipped, even if they contain non-null keys, or headers
 * <p>
 * This functionality is used in druid-avro-extensions to automatically decode messages using the Pulsar schema registry.
 */
public class PulsarRecordEntity extends ByteEntity
{
  private final Message<byte[]> message;

  public PulsarRecordEntity(Message<byte[]> message)
  {
    super(message.getData());
    this.message = message;
  }

  public Message<byte[]> getMessage()
  {
    return message;
  }
}
