#!/bin/bash
# This file defines the hostnames/locations for the various services.

ZOOKEEPER_PORT=2181
ZK_CONNECT_STRING="localhost:2181"

DRUID_DB_URI="jdbc:mysql://localhost:3306/druid"
DRUID_DB_USER="druid"
DRUID_DB_PASS="diurd"

DRUID_BROKER_HOST="localhost"
DRUID_BROKER_PORT=8080

DRUID_MASTER_HOST=`hostname`
DRUID_MASTER_PORT=8081

DRUID_REALTIME_HOST=`hostname`
DRUID_REALTIME_PORT=8082

DRUID_COMPUTE_HOST=`hostname`
DRUID_COMPUTE_PORT=8083

AWS_KEY="AKIAJSUNH5YW36MCNTZA"
AWS_SECRET="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"

S3_BUCKET="dev_logs"
S3_BASENAME="druid_"

KAFKA_TOPIC="campaigns_01"

FIREHOSE_RATE_PER_SEC=500
