/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.druid.msq.exec;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.druid.client.coordinator.CoordinatorClient;
import org.apache.druid.msq.kernel.WorkOrder;
import org.apache.druid.query.policy.PolicyEnforcer;
import org.apache.druid.query.rowsandcols.semantic.WireTransferable;
import org.apache.druid.query.rowsandcols.serde.WireTransferableContext;
import org.apache.druid.segment.IndexIO;
import org.apache.druid.segment.IndexMerger;
import org.apache.druid.segment.SegmentWrangler;
import org.apache.druid.segment.incremental.RowIngestionMeters;
import org.apache.druid.segment.loading.DataSegmentPusher;
import org.apache.druid.segment.loading.external.VirtualStorageManager;
import org.apache.druid.server.SegmentManager;

import javax.annotation.Nullable;
import java.io.Closeable;
import java.io.File;

/**
 * Provides services and objects for the functioning of the frame processors. Scoped to a specific stage of a
 * specific query, i.e., one {@link WorkOrder}.
 *
 * Generated by {@link WorkerContext#frameContext(WorkOrder)}.
 */
public interface FrameContext extends Closeable
{
  PolicyEnforcer policyEnforcer();

  SegmentWrangler segmentWrangler();

  RowIngestionMeters rowIngestionMeters();

  /**
   * Returns the segment manager for loading and caching segments.
   */
  SegmentManager segmentManager();

  /**
   * Returns the virtual storage manager for caching files.
   */
  VirtualStorageManager virtualStorageManager();

  /**
   * Returns the coordinator client for fetching DataSegment metadata when not available locally.
   * May be null if no coordinator client is available (e.g., in Dart workers).
   */
  @Nullable
  CoordinatorClient coordinatorClient();

  DataServerQueryHandlerFactory dataServerQueryHandlerFactory();

  /**
   * Temporary directory, fully owned by this particular stage.
   */
  File tempDir();

  ObjectMapper jsonMapper();

  /**
   * Context for {@link WireTransferable} serde.
   */
  WireTransferableContext wireTransferableContext();

  IndexIO indexIO();

  File persistDir();

  DataSegmentPusher segmentPusher();

  IndexMerger indexMerger();

  /**
   * Acquire processing buffers sized for {@code requestedSlices} concurrent processors. Must be called exactly
   * once for stages that use processing buffers, before any call to {@link #processingBuffers()}. Stages that
   * don't use processing buffers must not call this method.
   */
  void acquireProcessingBuffers(int requestedSlices);

  /**
   * Returns the {@link ProcessingBuffers} previously acquired via {@link #acquireProcessingBuffers}. Throws if
   * not yet acquired.
   */
  ProcessingBuffers processingBuffers();

  WorkerMemoryParameters memoryParameters();

  WorkerStorageParameters storageParameters();

  /**
   * Configuration for writing frames.
   */
  FrameWriterSpec frameWriterSpec();

  default File tempDir(String name)
  {
    return new File(tempDir(), name);
  }

  /**
   * Releases resources used in processing. This is called when processing has completed, but before results are
   * cleaned up. Specifically, it is called by {@link WorkerImpl.KernelHolder#processorCloser}.
   */
  @Override
  void close();
}
