/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.druid.msq.querykit;

import com.google.common.base.Preconditions;
import com.google.common.util.concurrent.Futures;
import com.google.common.util.concurrent.ListenableFuture;
import com.google.common.util.concurrent.SettableFuture;
import com.google.errorprone.annotations.concurrent.GuardedBy;
import org.apache.druid.common.guava.FutureUtils;
import org.apache.druid.frame.processor.FrameProcessor;
import org.apache.druid.frame.processor.manager.ProcessorAndCallback;
import org.apache.druid.frame.processor.manager.ProcessorManager;
import org.apache.druid.java.util.common.logger.Logger;
import org.apache.druid.utils.CloseableUtils;

import javax.annotation.Nullable;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.function.Function;

/**
 * Manager that chains processors: runs all processors generated by {@link #first} first, then based on its result,
 * creates {@link #restFuture} using {@link #restFactory} and runs that next.
 */
public class ChainedProcessorManager<A, B, R> implements ProcessorManager<Object, R>
{
  private static final Logger log = new Logger(ChainedProcessorManager.class);

  /**
   * First processor manager. The {@link FrameProcessor}s it creates run before all the others. The reference is
   * set to null once this manager has returned all of its processors.
   */
  @Nullable
  @GuardedBy("lock")
  private ProcessorManager<A, List<A>> first;

  /**
   * Produces {@link #restFuture}.
   */
  private final Function<List<A>, ProcessorManager<B, R>> restFactory;

  /**
   * The rest of the processors. Produced by {@link #restFactory} once {@link #first} has completed.
   */
  private final SettableFuture<ProcessorManager<B, R>> restFuture = SettableFuture.create();

  /**
   * Lock used to synchronize the things used by {@link #next()}. We need enough thread safety to allow the
   * future returned by {@link #next()} to be resolved in a future callback handler.
   */
  private final Object lock = new Object();

  /**
   * Whether {@link #close()} has been called.
   */
  @GuardedBy("lock")
  private boolean closed;

  /**
   * Number of processors handed out by {@link #first}. {@link #firstProcessorResult} is complete once this many
   * results have been accumulated.
   */
  @GuardedBy("lock")
  private int firstProcessorCount;

  /**
   * Results of the processors created by {@link #first}. Read and written under {@link #lock}, but the list itself
   * is handed to {@link #restFactory}, so it may be read by the resulting manager on another thread.
   */
  private final List<A> firstProcessorResult = new CopyOnWriteArrayList<>();

  public ChainedProcessorManager(
      final ProcessorManager<A, ?> firstProcessor,
      final Function<List<A>, ProcessorManager<B, R>> restFactory
  )
  {
    Preconditions.checkNotNull(firstProcessor, "first");

    this.first = firstProcessor.withAccumulation(
        firstProcessorResult,
        (acc, a) -> {
          synchronized (lock) {
            acc.add(a);
            checkFirstProcessorComplete();
          }
          return acc;
        }
    );
    this.restFactory = Preconditions.checkNotNull(restFactory, "restFactory");
  }

  @Override
  public ListenableFuture<Optional<ProcessorAndCallback<Object>>> next()
  {
    final ListenableFuture<Optional<ProcessorAndCallback<A>>> nextFromFirst;

    synchronized (lock) {
      if (closed) {
        throw new IllegalStateException();
      } else if (first == null) {
        return nextFromRest();
      }

      nextFromFirst = first.next();
    }

    return FutureUtils.transformAsync(
        nextFromFirst,
        processorAndCallback -> {
          synchronized (lock) {
            if (!closed) {
              if (processorAndCallback.isPresent()) {
                // More processors left to run.
                firstProcessorCount++;
                //noinspection unchecked
                return Futures.immediateFuture(Optional.of((ProcessorAndCallback<Object>) processorAndCallback.get()));
              } else {
                first = null;
                checkFirstProcessorComplete();
                return nextFromRest();
              }
            }
          }

          // Closed while we were waiting. Clean up the processor we were handed.
          if (processorAndCallback.isPresent()) {
            final FrameProcessor<A> processor = processorAndCallback.get().processor();
            CloseableUtils.closeAndSuppressExceptions(
                processor::cleanup,
                e -> log.noStackTrace().warn(e, "Failed to clean up processor[%s] after close", processor)
            );
          }

          return Futures.immediateFuture(Optional.empty());
        }
    );
  }

  /**
   * Returns the next processor from {@link #restFuture}, once that manager is available.
   */
  private ListenableFuture<Optional<ProcessorAndCallback<Object>>> nextFromRest()
  {
    //noinspection unchecked, rawtypes
    return FutureUtils.transformAsync(
        restFuture,
        rest -> (ListenableFuture) rest.next()
    );
  }

  /**
   * Sets {@link #restFuture} once all processors from {@link #first} have been created and have finished running.
   * Does nothing once {@link #close()} has been called, since nothing would close the new manager.
   */
  @GuardedBy("lock")
  private void checkFirstProcessorComplete()
  {
    if (!closed && first == null && (firstProcessorResult.size() == firstProcessorCount)) {
      restFuture.set(restFactory.apply(firstProcessorResult));
    }
  }

  @Override
  public R result()
  {
    return FutureUtils.getUncheckedImmediately(restFuture).result();
  }

  @Override
  public void close()
  {
    final ProcessorManager<A, List<A>> firstToClose;
    final ProcessorManager<B, R> restToClose;

    synchronized (lock) {
      if (closed) {
        return;
      }

      closed = true;
      firstToClose = first;
      restToClose = restFuture.isDone() ? FutureUtils.getUncheckedImmediately(restFuture) : null;
    }

    // Cancel in case restFuture was never set, so futures from nextFromRest() do not remain pending forever.
    restFuture.cancel(false);

    CloseableUtils.closeAndWrapExceptions(() -> CloseableUtils.closeAll(firstToClose, restToClose));
  }
}
