/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.druid.msq.querykit;

import com.google.common.base.Preconditions;
import org.apache.druid.frame.channel.ReadableFrameChannel;
import org.apache.druid.frame.read.FrameReader;
import org.apache.druid.java.util.common.ISE;
import org.apache.druid.msq.exec.DataServerQueryHandler;
import org.apache.druid.msq.input.InputSlice;
import org.apache.druid.msq.input.InputSliceReader;

import javax.annotation.Nullable;

/**
 * A single item of readable input. Generated by {@link InputSliceReader#attach} from an {@link InputSlice}.
 * <br>
 * Each item is either readable as a {@link org.apache.druid.segment.Segment} or as a {@link ReadableFrameChannel},
 * but not both. Check {@link #hasSegment()} and {@link #hasChannel()} to see which one you have.
 */
public class ReadableInput
{
  /**
   * Constant indicating that no stage number is associated with this input.
   */
  public static final int NO_STAGE = -1;

  /**
   * Constant indicating that no partition number is associated with this input.
   */
  public static final int NO_PARTITION = -1;

  @Nullable
  private final SegmentReferenceHolder segment;

  @Nullable
  private final DataServerQueryHandler dataServerQuery;

  @Nullable
  private final ReadableFrameChannel channel;

  @Nullable
  private final FrameReader frameReader;

  private final int stageNumber;
  private final int partitionNumber;

  private ReadableInput(
      @Nullable SegmentReferenceHolder segment,
      @Nullable DataServerQueryHandler dataServerQuery,
      @Nullable ReadableFrameChannel channel,
      @Nullable FrameReader frameReader,
      final int stageNumber,
      final int partitionNumber
  )
  {
    this.segment = segment;
    this.dataServerQuery = dataServerQuery;
    this.channel = channel;
    this.frameReader = frameReader;
    this.stageNumber = stageNumber;
    this.partitionNumber = partitionNumber;

    if ((segment == null) && (channel == null) && (dataServerQuery == null)) {
      throw new ISE("Provide 'segment', 'dataServerQuery' or 'channel'");
    }
  }

  /**
   * Create an input associated with a physical segment.
   *
   * @param segment the segment
   */
  public static ReadableInput segment(final SegmentReferenceHolder segment)
  {
    return new ReadableInput(Preconditions.checkNotNull(segment, "segment"), null, null, null, NO_STAGE, NO_PARTITION);
  }

  /**
   * Create an input associated with a query to a data server
   *
   * @param dataServerQueryHandler the data server query handler
   */
  public static ReadableInput dataServerQuery(final DataServerQueryHandler dataServerQueryHandler)
  {
    return new ReadableInput(null, Preconditions.checkNotNull(dataServerQueryHandler, "dataServerQuery"), null, null, NO_STAGE, NO_PARTITION);
  }

  /**
   * Create an input associated with a channel.
   *
   * @param channel         the channel
   * @param frameReader     reader for the channel
   * @param stageNumber     stage number associated with the channel
   * @param partitionNumber partition number associated with the channel
   */
  public static ReadableInput channel(
      final ReadableFrameChannel channel,
      final FrameReader frameReader,
      final int stageNumber,
      final int partitionNumber
  )
  {
    return new ReadableInput(
        null,
        null,
        Preconditions.checkNotNull(channel, "channel"),
        Preconditions.checkNotNull(frameReader, "frameReader"),
        stageNumber,
        partitionNumber
    );
  }

  /**
   * Whether this input is a segment (from {@link #segment(SegmentReferenceHolder)}).
   */
  public boolean hasSegment()
  {
    return segment != null;
  }

  /**
   * Whether this input is a dataserver query (from {@link #dataServerQuery(DataServerQueryHandler)}).
   */
  public boolean hasDataServerQuery()
  {
    return dataServerQuery != null;
  }

  /**
   * Whether this input is a channel (from {@link #channel(ReadableFrameChannel, FrameReader, int, int)}.
   */
  public boolean hasChannel()
  {
    return channel != null;
  }

  /**
   * The segment for this input. Only valid if {@link #hasSegment()}.
   */
  public SegmentReferenceHolder getSegment()
  {
    checkIsSegment();
    return segment;
  }

  /**
   * The data server query for this input. Only valid if {@link #hasDataServerQuery()}}.
   */
  public DataServerQueryHandler getDataServerQuery()
  {
    checkIsDataServerQuery();
    return dataServerQuery;
  }

  /**
   * The channel for this input. Only valid if {@link #hasChannel()}.
   */
  public ReadableFrameChannel getChannel()
  {
    checkIsChannel();
    return channel;
  }

  /**
   * The frame reader for this input. Only valid if {@link #hasChannel()}.
   */
  public FrameReader getChannelFrameReader()
  {
    checkIsChannel();
    return frameReader;
  }

  /**
   * The stage number for this input. Only valid if {@link #hasChannel()}.
   */
  public int getStageNumber()
  {
    checkIsChannel();
    return stageNumber;
  }

  /**
   * The partition number for this input. Only valid if {@link #hasChannel()}.
   */
  public int getPartitionNumber()
  {
    checkIsChannel();
    return partitionNumber;
  }

  private void checkIsSegment()
  {
    if (!hasSegment()) {
      throw new ISE("Not a segment; cannot call this method");
    }
  }

  private void checkIsDataServerQuery()
  {
    if (!hasDataServerQuery()) {
      throw new ISE("Not a data server query; cannot call this method");
    }
  }

  private void checkIsChannel()
  {
    if (!hasChannel()) {
      throw new ISE("Not a channel input; cannot call this method");
    }
  }
}
