/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.druid.queryng.operators;

import org.apache.druid.queryng.fragment.FragmentContext;

import java.util.function.Predicate;

/**
 * Super-simple filter operator which allows tests to build up a
 * stack of operators starting with values generated by MockOperator.
 */
public class MockFilterOperator<T> extends MappingOperator<T, T>
{
  private final Predicate<T> predicate;
  private T nextValue;

  public MockFilterOperator(FragmentContext context, Operator<T> input, Predicate<T> pred)
  {
    super(context, input);
    this.predicate = pred;
  }

  @Override
  public boolean hasNext()
  {
    while (super.hasNext()) {
      nextValue = inputIter.next();
      if (predicate.test(nextValue)) {
        return true;
      }
    }
    return false;
  }

  @Override
  public T next()
  {
    return nextValue;
  }
}
