SELECT c8, c1,
       LAST_VALUE(c1) OVER W as w_lval_c1,
       LAST_VALUE(c2) OVER W2 as w2_lval_c2,
       LAST_VALUE(c3) OVER W3 as w3_lval_c3,
       LAST_VALUE(c4) OVER W_DFLT_FRM AS wDfrm_lval_c4,
       LAST_VALUE(c5) OVER W2 as w2_lval_c5,
       LAST_VALUE(c7) OVER W3 as w3_lval_c7,
       LAST_VALUE(c8) OVER W3 as w3_lval_c8,
       LAST_VALUE(c9) OVER W_DFLT_FRM AS wDfrm_lval_c9
FROM "t_alltype.parquet"
       WINDOW W AS ( PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ),
       W2 AS ( PARTITION BY c8 ORDER BY c1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ),
       W3 AS ( PARTITION BY c8 ORDER BY c1 RANGE BETWEEN CURRENT ROW AND CURRENT ROW ),
       W_DFLT_FRM AS ( PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW )
