SELECT c8, c1,
       MAX(c1) OVER W as w_max_c1,
       MAX(c2) OVER W2 as w2_max_c2,
       MAX(c3) OVER W3 as w3_max_c3,
       MAX(c4) OVER W_DFLT_FRM AS wDfrm_max_c4,
       MAX(c5) OVER W2 as w2_max_c5,
       MAX(c7) OVER W3 as w3_max_c7,
       MAX(c9) OVER W_DFLT_FRM AS wDfrm_max_c9
FROM "t_alltype.parquet"
       WINDOW W AS ( PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ),
       W2 AS ( PARTITION BY c8 ORDER BY c1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ),
       W3 AS ( PARTITION BY c8 ORDER BY c1 RANGE BETWEEN CURRENT ROW AND CURRENT ROW ),
       W_DFLT_FRM AS ( PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW )
