SELECT c8, c1,
       MIN(c1) OVER W as w_min_c1,
       MIN(c2) OVER W2 as w2_min_c2,
       MIN(c3) OVER W3 as w3_min_c3,
       MIN(c4) OVER W_DFLT_FRM AS wDfrm_min_c4,
       MIN(c5) OVER W2 as w2_min_c5,
       MIN(c7) OVER W3 as w3_min_c7,
       MIN(c9) OVER W_DFLT_FRM AS wDfrm_min_c9
FROM "t_alltype.parquet"
       WINDOW W AS ( PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ),
       W2 AS ( PARTITION BY c8 ORDER BY c1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ),
       W3 AS ( PARTITION BY c8 ORDER BY c1 RANGE BETWEEN CURRENT ROW AND CURRENT ROW ),
       W_DFLT_FRM AS ( PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW )
