SELECT 
      SUM(c2) OVER w as w_sum, 
      MIN(c1) OVER (PARTITION BY c8 ORDER BY c1 DESC NULLS LAST RANGE BETWEEN CURRENT ROW AND CURRENT ROW), 
      MAX(c9) OVER (PARTITION BY c8 ORDER BY c1,c9 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), 
      AVG(c1) OVER (PARTITION BY c8 ORDER BY c1 DESC NULLS FIRST RANGE BETWEEN CURRENT ROW AND CURRENT ROW), 
      COUNT(c2) OVER w as w_cnt,
      FIRST_VALUE(c2) OVER (PARTITION BY c8 ORDER BY c2 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
      LAST_VALUE(c2) OVER w as lval
FROM ( SELECT * FROM `t_alltype.parquet` ) TAL
      WINDOW w AS (PARTITION BY c8 ORDER BY c2 DESC NULLS FIRST RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING);
