SELECT c8, c1,
       SUM(c1) OVER W as w_sum_c1,
       SUM(c2) OVER W2 as w2_sum_c2,
       SUM(c3) OVER W3 as w3_sum_c3,
       SUM(c9) OVER W_DFLT_FRM AS wDfrm_sum_c9,
       SUM(c9) OVER W as w_sum_c9,
       SUM(c3) OVER W2 as w2_sum_c3,
       SUM(c2) OVER W3 as w3_sum_c2,
       SUM(c1) OVER W_DFLT_FRM AS wDfrm_sum_c1
FROM "t_alltype.parquet"
       WINDOW W AS ( PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ),
       W2 AS ( PARTITION BY c8 ORDER BY c1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ),
       W3 AS ( PARTITION BY c8 ORDER BY c1 RANGE BETWEEN CURRENT ROW AND CURRENT ROW ),
       W_DFLT_FRM AS ( PARTITION BY c8 ORDER BY c1 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW )
