Austria	null	#de.wikipedia	["N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria"]
Austria	Horsching	#de.wikipedia	["N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria"]
Austria	Vienna	#de.wikipedia	["N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria"]
Austria	Vienna	#es.wikipedia	["N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria"]
Austria	Vienna	#tr.wikipedia	["N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria"]
Republic of Korea	null	#ko.wikipedia	["N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea"]
Republic of Korea	Jeonju	#ko.wikipedia	["N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea"]
Republic of Korea	Seoul	#ko.wikipedia	["N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea"]
Republic of Korea	null	#en.wikipedia	["N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea"]
Republic of Korea	null	#ja.wikipedia	["N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Austria","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea","N/A","Republic of Korea"]
