// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";
package proto3test;
option java_package = "org.apache.druid.data.input.protobuf";
option java_outer_classname = "Proto3TestEventWrapper";

message Proto3TestEvent {
    enum Category {
        CATEGORY_ZERO = 0;
        CATEGORY_ONE = 1;
    }

    message Nested {
        int32 value = 1;
    }

    int32 someInt = 1;
    string someString = 2;
    Category category = 3;
    optional int32 optionalInt = 4;
    Nested nested = 5;
    repeated int32 someList = 6;
}
