#!/bin/bash -eu

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "$#" -ne 1 ]; then
  echo "Illegal number of parameters, should be just one: the version";
  exit 1;
fi

echo "Building to docs for '$1'..."

npm run compile-scss

npm run build | tee ./build-log.txt

if grep -q "unresolved links in file" ./build-log.txt; then
  echo "There are unresolved links, please fix";
  rm build-log.txt;
  #exit 1
else
  rm build-log.txt
fi

node script/fix-path.js $1

echo "Cleaning..."
rm -rf ../../incubator-druid-website-src/docs/$1/
mkdir -p ../../incubator-druid-website-src/docs/$1/

cp -r ./build/ApacheDruid/docs/* ../../incubator-druid-website-src/docs/$1/

mkdir -p ../../incubator-druid-website-src/css
cp ./build/ApacheDruid/css/* ../../incubator-druid-website-src/css

mkdir -p ../../incubator-druid-website-src/js
cp ./build/ApacheDruid/js/* ../../incubator-druid-website-src/js

pushd $(pwd)
cd ../../incubator-druid-website-src/
git add docs/$1/
git add -u .
popd
