{{- if and (.Values.rbac.create) (.Values.middleManager.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "druid.middleManager.fullname" . }}
  labels:
    app: {{ include "druid.name" . }}
    chart: {{ include "druid.chart" . }}
    component: {{ .Values.middleManager.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "druid.middleManager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "druid.middleManager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
