# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Maven Package

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - verta/main
      - 'release/*'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        server-id: github-verta-druid # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: ./verta_build_and_publish.sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
        LOCAL_MAVEN_SETTINGS: $GITHUB_WORKSPACE/settings.xml
